CREATE TABLE `dressingroom_items` (
  `accountId` varchar(50) NOT NULL,
  `itemId` int(11) NOT NULL,
  `color1` int(10) unsigned NOT NULL DEFAULT '0',
  `color2` int(10) unsigned NOT NULL DEFAULT '0',
  `color3` int(10) unsigned NOT NULL DEFAULT '0',
  `price` int(11) NOT NULL DEFAULT '0',
  `sellPrice` int(11) NOT NULL DEFAULT '0',
  `amount` int(11) NOT NULL DEFAULT '1',
  `flags` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `state` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `figureB` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `durability` int(11) NOT NULL DEFAULT '0',
  `durabilityMax` int(11) NOT NULL DEFAULT '0',
  `durabilityOriginal` int(11) NOT NULL DEFAULT '0',
  `attackMin` smallint(6) unsigned NOT NULL DEFAULT '0',
  `attackMax` smallint(6) unsigned NOT NULL DEFAULT '0',
  `injuryMin` smallint(5) unsigned NOT NULL DEFAULT '0',
  `injuryMax` smallint(5) unsigned NOT NULL DEFAULT '0',
  `balance` tinyint(4) NOT NULL DEFAULT '0',
  `critical` tinyint(4) NOT NULL DEFAULT '0',
  `defense` int(11) NOT NULL DEFAULT '0',
  `protection` smallint(6) NOT NULL DEFAULT '0',
  `range` smallint(6) NOT NULL DEFAULT '0',
  `attackSpeed` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `experience` int(11) NOT NULL DEFAULT '0',
  `upgrades` tinyint(4) NOT NULL DEFAULT '0',
  `meta1` varchar(2048) DEFAULT NULL,
  `meta2` varchar(2048) DEFAULT NULL,
  `prefix` smallint(5) unsigned NOT NULL DEFAULT '0',
  `suffix` smallint(5) unsigned NOT NULL DEFAULT '0',
  `upgradeEffects` text,
  UNIQUE KEY `accountId` (`accountId`,`itemId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

